arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev9
    - Rev8
    - Rev11
    - Rev3
    - Rev10
    - Rev6
  gains:
    Rev9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev7
  gains:
    Rev7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1